FLIP_SIZE = 1
FLIP_CONSISTENCE = True
RECENT_ACTION_NUM = 20
REPEAT_PUNISHMENT = -1000
GOAL_REWARD = 1000

MEMORY_LENGTH = 40000
THRESH = 0.5
END_THRESH = 0.3

FULL_SIZE = (2048, 2048)
KERNEL_SIZE = (256, 256)

GPU = 0

BATCH_SIZE = 32
UPDATE_TARGET_ITER = 40
OPTIMIZE_MODEL_ITER = 50
MAX_TIMESTEP = 500
EPISODE = 15

EPOCH = 1

LEARNING_RATE = 0.001

GAMMA = 0.99
EPS_START = 1
EPS_END = 0.1
EPS_DECAY = 15000

FINE_TUNE_EPS_START = 0.1
FINE_TUNE_EPS_END = 0.01
FINE_TUNE_EPS_DECAY = 5

FINE_TUNE_AUGMENTATION = False

PRE_TRAIN = True

FINE_TUNE = False
FINE_TUNE_EPOCH = 5
INFERENCE_EPOCH = 10
BINARY_IMG = True

ACTION_MASK = True

L2_LOSS_REWARD_RATIO = 0.9
PVBAND_REWARD_RATIO = 0.1

DOUBLE_DQN = True

MASK_SAVE_BY = 'l2loss'
# 'reward' or 'l2loss' or 'pvband'

MULTIGPU = False
